#first build 
FROM node:14 AS react-build
WORKDIR /usr/src/app
COPY ["./package.json","./package-lock.json", "./"]
RUN npm install
COPY . .
RUN npm run build
EXPOSE 8080 443 80
FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /usr/src/app/build /usr/share/nginx/html

